name: rich_text_controller
description: An extended text editing controller that supports different inline styles for custom regex patterns.
version: 3.0.1
homepage: https://github.com/micazi/rich_text_controller

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
